In [31]:
from src.structools.tools.date_tools import DateModel, find_dates_index
from src.structools.tools.market import load_stocks_data
from dateutil.relativedelta import relativedelta
from datetime import datetime
 
import numpy as np
import pandas as pd

In [33]:
ticker="AAPL"
start = DateModel(date="2000-01-01")
end = DateModel(date=datetime.today())
df = load_stocks_data(ticker, start, end)

In [37]:
dt_day = pd.Timestamp(df.index[0].value).to_pydatetime()
dt_day

datetime.datetime(2000, 1, 3, 0, 0)

In [38]:
dt_day + relativedelta(years=5)

datetime.datetime(2005, 1, 3, 0, 0)

In [46]:
arr = np.arange(10)
arr.shape[0]

10

[[0 1 2 3]
 [7 4 5 6]]


In [73]:
arr = np.array([[1,2,3], [4,5,6]])
arr[0, : ]+=10
arr[0, :] = np.arange(1, 4)
arr[1, 0] = 5
arr

array([[1, 2, 3],
       [5, 5, 6]])

In [54]:
arr = np.array([1, 0,2, 0,6, 0,5,1,5, 1,5, 1, -999, -999])
arr[:np.argmin(arr)]

array([1, 0, 2, 0, 6, 0, 5, 1, 5, 1, 5, 1])

In [66]:
arr=np.arange(20)
sum(arr % 40 >50)

0

In [70]:
N = 2
add_arr = np.array([[1][2]])
add = np.ones((N, 1)) * (-1)
np.hstack((add, arr))


IndexError: list index out of range

In [72]:
add = np.ones((N, 1)) * (-1)
add

array([[-1.],
       [-1.]])

In [74]:
np.hstack((add, arr))


array([[-1.,  1.,  2.,  3.],
       [-1.,  5.,  5.,  6.]])